DJW 10 spectral windows new technical goal
orppst/pst-gui pull request #40
Opened 2023-11-08 18:04 UTC by DJWalker42

New technical goal and edit technical goal go to the same form where both Performance Parameters and Spectral Windows can be viewed. Currently only Performance Parameters can be added/edited. Spectral Windows to be added/edited once #12 gets fixed. 

This also includes a fix to the forms not being initialised with valid data, essentially the 'unit' member of NumberUnitType needs to initialised to null rather than the empty string.

2023-11-09 15:58 UTC, alan-stokes requested changes
ive also added a pr: https://github.com/orppst/pst-gui/pull/43 which contains even more doc changes that i did for ya.

2023-11-09 15:58 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/spectrum.form.tsx
>                              "I","Q","U","V","RR","LL","RL","LR","XX","YY","XY","YX","PF","PP","PA"
cant we use PolStateEnum here?

2023-11-09 15:58 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/spectrum.form.tsx
> +                <Grid.Col span={{base: TOTAL_COLUMNS, xl: TOTAL_COLUMNS/4}}>
could we not name this as a constant next to total columns, as its used a few times. and would then be cleaner to read.

2023-11-09 15:58 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/spectrum.form.tsx
> +                <Grid.Col span={{base: TOTAL_COLUMNS/2, xl: TOTAL_COLUMNS/2/4}}>
"TOTAL_COLUMNS/2/4 " can we have a  named constant for this, and an explanation of why its /2/4?

2023-11-09 15:58 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/technicalGoalTable.tsx
> +export type TechnicalGoalId = {id: number};
why do we need a type just for a number?

2023-11-09 16:00 UTC, alan-stokes commented
its also worth noting that i've yet to be able to test this. as i've hit that 401 issue again. we should allocate some time to figure out whats going on here.

2023-11-09 18:08 UTC, DJWalker42 commented on src/main/webui/src/technicalGoals/edit.group.tsx
> +    const TOTAL_COLUMNS = 10;
I kind of liked the aesthetics that ratio gave me. In fact, if I was simplifying that ratio all the way the total columns would be 5 and the number of columns for the performance parameters would be 2. We could get finer control over that ratio by making the total columns a number greater than 10 or 12 for than matter. I've no idea why 12 was settled upon as a default other than it has more factors than 10. If it's about factors why not use 60 - works for clock time.

2023-11-09 19:01 UTC, DJWalker42 commented on src/main/webui/src/technicalGoals/spectrum.form.tsx
>                              "I","Q","U","V","RR","LL","RL","LR","XX","YY","XY","YX","PF","PP","PA"
In short no. 

In a longer answer,  the Select element requires a data array that is an array of string. There is a way to extract the names of an Enum type as an array of strings but then you have to truncated it to get rid of the numeric keys that come in the second half of that array. However, and more fundamentally than that, despite its name 'PolStateEnum' is not actually an Enum in the 'proposalToolSchema.ts' but a string union type. I couldn't be bothered to work out how to extract the strings from a string union into an array for the sake of a 15 strings that are no more than two characters in length.  Additionally, its unlikely we'll need to modify that string union in any way so I hard coded it.  

That being said, if the data model were to change and the PolStateEnum in the Java API code, which is an enum, contained additional elements, we'd have to regenerate 'proposalToolSchemea.ts', then hand edit that data array in the Select in the Typescript to reflect the changes. It might be nice to have that happen automatically i.e. work out how to create an array of strings from a string union. Here's some peoples attempts on [StackOverflow](https://stackoverflow.com/questions/44480644/string-union-to-string-array)

2023-11-09 19:01 UTC, DJWalker42 commented on src/main/webui/src/technicalGoals/spectrum.form.tsx
> +                <Grid.Col span={{base: TOTAL_COLUMNS, xl: TOTAL_COLUMNS/4}}>
{start: value, unit} + {end: value, unit} + {resolution: value, unit} + { {polarisation state} {isSkyFrequency} } = 4 things

The first 3 things ({...}) share one quarter of the total number of columns each. The last thing we consider as two sub things that share equally the last quarter of the total number of columns.

2023-11-09 19:01 UTC, DJWalker42 commented on src/main/webui/src/technicalGoals/spectrum.form.tsx
> +                <Grid.Col span={{base: TOTAL_COLUMNS/2, xl: TOTAL_COLUMNS/2/4}}>
Following on from the comment above, I've done this such that when the view-port is sufficiently narrow the things stack like this:

{start: value, unit} 
{end: value, unit}
{resolution: value, unit}
{ {polarisation state} {isSkyFrequency} }

2023-11-10 10:58 UTC, alan-stokes commented on src/main/webui/src/commonInputs/NumberInputPlusUnit.tsx
> + * convert NumberUnitType to RealQuantity
can you document the param and return please.

2023-11-10 13:47 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/edit.group.tsx
> +    const TOTAL_COLUMNS = 10;
this is a strange one. coz im ust to letting bootstrap figure out all the layouts. that all being said. with a wee fiddling, id personally perfer the following

`const TOTAL_COLUMNS = 12;
    const PERFORMANCE_COLUMNS = 3;
    const SPECTRUM_COLUMNS = TOTAL_COLUMNS - PERFORMANCE_COLUMNS`

as it stops the windows feeling like they are squeezed. but will leave that as a separate discussion. https://github.com/orgs/orppst/discussions/13

2023-11-10 13:51 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/spectrum.form.tsx
>                              "I","Q","U","V","RR","LL","RL","LR","XX","YY","XY","YX","PF","PP","PA"
have looked at your links and done some fiddling myself and your right, its a mess of pain. so I've made issue: https://github.com/orppst/pst-gui/issues/47 to see if we can just solve the problem at the source. But means not blocker for your work

2023-11-10 13:53 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/spectrum.form.tsx
> +                <Grid.Col span={{base: TOTAL_COLUMNS/2, xl: TOTAL_COLUMNS/2/4}}>
im not arguing about that. just that TOTAL_COLUMNS/2/4 could be a named constant such as "NARROW_LAYOUT_COLUMNS" or equiv. so its easier to understand at a glance what thats axctually trying to do.

2023-11-10 13:56 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/technicalGoalTable.tsx
> +export type TechnicalGoalId = {id: number};
thats interesting, coz that type must have had 2 values at some point given this code:

'return (
                                <ObservationRow id={observation.dbid!}
                                                key={observation.dbid!} />
                            )'

as that type is only used here. lol. If we dont need it, i propose we remove the type, and make less code to maintain. thoughts?

2023-11-10 13:57 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/spectrum.form.tsx
> +                <Grid.Col span={{base: TOTAL_COLUMNS, xl: TOTAL_COLUMNS/4}}>
this is the same disucssion. TOTAL_COLUMNS/4 being something like "VALUE_UNIT_PAIR_NARROW_COLUMNS"

2023-11-10 14:11 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/technicalGoalTable.tsx
> +export type TechnicalGoalId = {id: number};
seems you do need the object, as it seems your not allowed to send primitives between functions. how weird.

2023-11-10 14:16 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/technicalGoalTable.tsx
> +export type TechnicalGoalId = {id: number};
https://github.com/orppst/pst-gui/pull/48 fixes the issue about the 2 numbers instead of 1. thanks for making me look at it. ;-)

2023-11-10 15:04 UTC, alan-stokes commented
this pr resolves https://github.com/orppst/pst-gui/issues/10

2023-11-10 16:00 UTC, merged