Resolves #51 add string limits to create proposal
orppst/pst-gui pull request #55
Opened 2023-11-15 11:24 UTC by AllanEngland

And a character counter from the the edit summary pane, and apply limit to new title and edit title.

2023-11-16 10:51 UTC, alan-stokes requested changes

2023-11-16 10:51 UTC, alan-stokes commented on src/main/webui/src/proposal/New.tsx
> +                           label={"Title"}
should we not now also have a "char remaining for this field as well now?

2023-11-16 10:51 UTC, alan-stokes commented on src/main/webui/src/proposal/Title.tsx
> +                           {...form.getInputProps('title')}/>
same question. chars remaining component?

2023-11-16 13:44 UTC, alan-stokes commented
the fact we're talking about putting this stuff in many places now. makes me wonder if we should have a component / function to fold this in by default? just needing the form name as a input afterall

2023-11-20 13:17 UTC, AllanEngland commented on src/main/webui/src/proposal/New.tsx
> +                           label={"Title"}
I thought about this when I did it, in my opinion I didn't think it necessary and would create clutter.  However, I'm no expert in this field and I've never written an observing proposal, so is 255 chars potentially restricting titles?

2023-11-28 16:39 UTC, AllanEngland commented
I tried a few different approaches and ended up going with the simplest.  A common characters remaining element has been added to the appropriate fields.

2023-11-29 10:59 UTC, alan-stokes commented on src/main/webui/src/commonInputs/remainingCharacterCount.tsx
> +    //isDimmed?: boolean
if this is commented out, why keep it?

2023-11-29 11:00 UTC, alan-stokes commented
looks fine (once that 1 liner is removed [assuming thats the case]) do have a question for beyond this pr. which is, why is it that the summary wraps around when it hits the end, but the title keeps scrolling? is this something we'd want to make consistent that all our input boxes wrap?

2023-11-29 11:35 UTC, AllanEngland commented
> looks fine (once that 1 liner is removed [assuming thats the case]) do have a question for beyond this pr. which is, why is it that the summary wraps around when it hits the end, but the title keeps scrolling? is this something we'd want to make consistent that all our input boxes wrap?

Surely anything beyond this pr should be a new discussion or issue?

2023-11-29 11:43 UTC, merged