Store spectral windows on the creation of a new technical goal
orppst/pst-gui pull request #62
Opened 2023-11-17 16:23 UTC by DJWalker42

Fixes #12.

- add a map of form spectral windows to convert to an appropriate type to save to the database
- includes a work-around with the 'index' field of a 'ScienceSpectralWindow'; sets it to Math.random() * 1000 - the semantics of "index" need to be clarified.

2023-11-23 09:45 UTC, alan-stokes requested changes

2023-11-23 09:45 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/scienceSpectralWindowGui.tsx
> + * @param {number | string} index unsure as to the semantics of this - has a non-null constraint in DB.
if this is anything like the NGOT system. a spectral window had both a group index and an index for 2 reasons, 1. was to identify the baseband it was in (from 1 to 4) and a index which stated where it was within the baseband window. This was partly due to the windows being stored as 1 array, and so you had to traverse the entire array to locate all windows for a given baseband and the same for the position within the baseband. Maybe this is something simular?

2023-11-23 09:45 UTC, alan-stokes commented on src/main/webui/src/technicalGoals/scienceSpectralWindowGui.tsx
> +        index: Math.random() * 1000, //work-around: unclear on the semantics of 'index'
I personally dislike this view of adding a randomly generated number here. Why cant we just add a default thats consistent but not feasible. such as -1? then future us can see this as a regular value and not wonder why the number keeps changing?

2023-11-28 09:42 UTC, pahjbo commented
will remove index from the model as we do not know what it is being used for.

2023-11-28 10:51 UTC, alan-stokes commented
have been thinking about this a bit, and I think i have a answer which feels like it would explain things a bit, though i still think removing it if we control the database implementation is a good call, as it means less data to transmit and receive. 

its often a good practice to avoid implementation details of data storage. for example stating a collection of data as an Collection, and not a an arrayList, or a HashMap or a Set. as each of these implementations have different views on order. And so maybe someone felt to put a index in to ensure if the data was stored in, say a set, that they could still recover the order? It may also be a reaction to python hashmaps, which at some point did not retain order, but then got switched back to FIFO when iterating. 

Anyhow, just my thought of for why that index may exist.

2023-12-07 11:21 UTC, merged